apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-api
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-api
  template:
    metadata:
      labels:
        app: web-api
    spec:
      containers:
      - name: web-api
        image: jvictorsm/backend
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres
              key: POSTGRES_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres
              key: POSTGRES_PASSWORD
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: postgres
              key: POSTGRES_DB
        - name: DB_HOST
          value: postgres
        - name: DB_PORT
          value: "5432"
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: "6379"
        - name: GITHUB_REPO
          value: jvictormarques/k8s-study
        resources:
          limits:
            cpu: "200m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        ports:
        - containerPort: 8000
        startupProbe:
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          httpGet:
            path: /
            port: 8000
        livenessProbe:
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8000
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 2
          httpGet:
            path: /ready
            port: 8000
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 10
            podAffinityTerm:
              topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - web-api
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-api
  namespace: dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web-app-api
  minReplicas: 3
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        periodSeconds: 15
        value: 100
    scaleDown:
      stabilizationWindowSeconds: 10
      policies:
      - type: Percent
        periodSeconds: 15
        value: 50
# ---
# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   name: backend
#   namespace: dev
# spec:
#   podSelector:
#     matchLabels:
#       app: web-api
#   policyTypes:
#   - Ingress
#   - Egress
#   ingress:
#   - from:
#     - ipBlock:
#         cidr: 0.0.0.0/0
#     ports:
#       - protocol: TCP
#         port: 8000
#   egress:
#   - to:
#     - podSelector:
#         matchLabels:
#           db: postgres
#     ports:
#     - protocol: TCP
#       port: 5432
#   - to:
#     - podSelector:
#         matchLabels:
#           db: redis
#     ports:
#     - protocol: TCP
#       port: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: web-app-api
  namespace: dev
spec:
  selector:
    app: web-api
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30000
  type: NodePort