# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   name: deny-different-namespaces
#   namespace: dev
# spec:
#   podSelector: {}
#   policyTypes:
#   - Ingress
#   - Egress
#   ingress:
#   - from:
#     - namespaceSelector:
#         matchLabels:
#           env: dev
#   egress:
#   - to:
#     - namespaceSelector:
#         matchLabels:
#           env: dev