apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota
  namespace: dev
spec:
  hard:
    requests.cpu: "1.650"
    requests.memory: "2.112Gi"
    requests.storage: "6Gi"
    limits.cpu: "2.7"
    limits.memory: "3.036Gi"