apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota
  namespace: dev
spec:
  hard:
    requests.cpu: "1"
    requests.memory: "1.25Gi"
    requests.storage: "2Gi"
    limits.cpu: "2"
    limits.memory: "2.5Gi"